### PR TITLE
Add initial tests with ava

### LINKED ISSUE #15: Need a test suite
A small test suite has been part of the plan, but I haven't gotten to it just yet.

### PR DESCRIPTION
**Pull request by cilice**
The implementation right now doesn’t make it possible to test baffle itself without running it in some browser environment.

Fixes #15

### CODE REVIEW

**Comment by danreeves** [comment]
`Baffle` could be tested in jsdom, right?

**Comment by cilice** [comment]
You are right, I totally forgot it existed 😅 I'll try to add it over the weekend

**Comment by camwiegert** [comment]
Yeah, seems like jsdom would be the way to go. Would love to see that.

**Comment by cilice** [comment]
I've added jsdom, adjusted the tests and added nyc with coverage, so you can setup coveralls.io or something.

```
---------------|----------|----------|----------|----------|----------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------|----------|----------|----------|----------|----------------|
All files      |    99.01 |    91.67 |      100 |      100 |                |
 baffle.js     |    98.08 |     87.5 |      100 |      100 |                |
 obfuscator.js |      100 |    95.45 |      100 |      100 |                |
 utils.js      |      100 |       90 |      100 |      100 |                |
---------------|----------|----------|----------|----------|----------------|
```

**Comment by cilice** [comment]
@camwiegert If ypu have any questions or notices, feel free to ask or change anything ⭐

**Comment by camwiegert** [comment]
I really appreciate this, thanks! Would you mind breaking this up a little bit. I'd love to see a PR that simply adds Ava and puts us in good position to write tests in the future. I'd like to have a PR-per-test group to discuss the best way to test everything.

**Pull request closed without merging**
