### PR TITLE
replace each with Array.prototype.forEach

### PR DESCRIPTION
**Pull request by zcoding**
Why not using the native `Array.prototype.forEach` method ?

### CODE REVIEW

**Comment by eugene-eeo** [comment]
IE 9+ (inclusive or not) supports ES5 array methods already. FWIW though, [can I use `Array.prototype.forEach`](http://caniuse.com/#search=array.foreach)?

**Comment by camwiegert** [comment]
My original intention, because `baffle` often runs a tight interval, was to use a raw for-loop for performance reasons.

I've never found conclusive benchmarks on the performance of `forEach`. Have any of you? I could be convinced to make the switch.

**Comment by cilice** [comment]
The main problem is that jsperf is down, but in my opinion that myth was busted a long time ago, that `[].forEach` was slower than `for`-loops.

Should we rather optimize to use `requestAnimationFrame`?

**Comment by eugene-eeo** [comment]
I think it's best to try forEach with and without `requestAnimationFrame`. If it seems laggy or unresponsive then we'd go back to using the for loop. My money's on the `each` function though because it doesn't need to do any `this` changes.

**Comment by camwiegert** [comment]
Closing this for the moment. I don't see this as critical until I find some good benchmarks.

**Pull request closed without merging**
